export {default as NavBar} from '$lib/components/NavBar.svelte';
export { default as ThemeSwitch } from '$lib/components/ThemeSwitch.svelte';
export { default as Home } from '$lib/components/Home.svelte';
export { default as About } from '$lib/components/About.svelte';
export { default as Skills } from '$lib/components/Skills.svelte';
export { default as Qualifications } from '$lib/components/Qualifications.svelte';
export { default as Services } from '$lib/components/Services.svelte';
export { default as Portfolio } from '$lib/components/Portfolio.svelte';
export { default as Projects } from '$lib/components/Projects.svelte';
export { default as Testimonial } from '$lib/components/Testimonial.svelte';
export { default as ContactMe } from '$lib/components/ContactMe.svelte';
export { default as Footer } from '$lib/components/Footer.svelte';